# Self-Describing Settings.yaml Structure
# =====================================
# No hardcoding in infrastructure - configuration drives everything

# Credential sources are self-describing with 'type' field
credentials:
  aws_basic:
    type: aws_credentials
    access_key_id: ***REMOVED***
    secret_access_key: ***REMOVED***
    default_region: us-east-1

  bedrock_llm:
    type: llm_service
    service_provider: aws_bedrock
    region: us-east-1
    default_model: anthropic.claude-3-sonnet-20240229-v1:0
    model_mapping:
      claude-3-haiku: anthropic.claude-3-haiku-20240307-v1:0
      claude-3-sonnet: anthropic.claude-3-sonnet-20240229-v1:0
      claude-3-5-sonnet: anthropic.claude-3-5-sonnet-20240620-v1:0
      claude-3-opus: anthropic.claude-3-opus-20240229-v1:0
    adapter_config:
      circuit_breaker: true
      retry_attempts: 3
      timeout: 60

  postgresql_primary:
    type: database_credentials
    engine: postgresql
    host: vectorqa-cluster.cluster-cu562e4m02nq.us-east-1.rds.amazonaws.com
    port: 5432
    database: vectorqa
    username: vectorqa_user
    password: ***REMOVED***
    ssl_mode: require

  sqlite_backup:
    type: database_credentials
    engine: sqlite
    database: ./data/backup.db
    host: ./data/backup.db
    username: backup_user
    password: YOUR_BACKUP_PASSWORD_HERE

  mlflow_api:
    type: api_credentials
    service: mlflow
    tracking_uri: http://localhost:5000
    artifact_store: s3://nsc-mvp1/onboarding-test/mlflow/

# Database configurations reference credentials by name
databases:
  primary:
    type: database_pool
    credential_ref: postgresql_primary  # <- References credential by name
    engine: postgresql
    min_connections: 2
    max_connections: 20
    pool_recycle: 3600
    pool_timeout: 30

  backup:
    type: database_pool
    credential_ref: sqlite_backup       # <- References credential by name
    engine: sqlite
    min_connections: 1
    max_connections: 1

# Services reference credentials by name
services:
  llm_processing:
    type: llm_service
    credential_ref: bedrock_llm          # <- References credential by name
    enabled: true

  aws_infrastructure:
    type: aws_service
    credential_ref: aws_basic            # <- References credential by name
    enabled: true

  data_tracking:
    type: tracking_service
    credential_ref: mlflow_api           # <- References credential by name
    enabled: true

# Integrations are self-describing
integrations:
  mlflow:
    type: tracking_integration
    credential_ref: mlflow_api           # <- References credential by name
    enabled: true
    backend_store_uri: "<<MANAGED_BY_CONNECTION_POOL>>"

  ldap:
    type: auth_integration
    enabled: false

  observability:
    type: monitoring_integration
    enabled: false